# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
 build:
  machine: true
   steps:
    - add_ssh_keys:
       - "c6:22:9d:e9:50:da:08:6d:50:74:60:36:9a:f0:fb:28"
    -checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t pepaporrasmedina/testdocker:$CIRCLE_SHA1 .
    - run: docker push pepaporrasmedina/testdocker:$CIRCLE_SHA1 
    - run: ssh -o StrictHostKeyChecking=no root@porrasmedina.com "/bin/bash /root/docker/deplay.sh $CIRCLE_SHA1"
